title: My Awesome Blog
author: Raman
email: rrp3095@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Its all about how started coding and how I fell in love with the journey in coding world

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
