title: Yeah Its my Awesome Blog
author: Raman
email: rrp3095@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yeah this my awesome blog about how started coding and how my love for journey in coding world increased over time.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
